### ISSUE TITLE
fixed_version field in Issue

### ISSUE THREAD

**Issue by ywata** [lookunder/RedmineHs#1]
I tried RedmineHs to generate my team's weekly report automatically using your module against almost brand-new Redmine 3.0.0 from Bitnami. Getting issue failed because of fixed_version field is missing in JSON.

It would be nice if fixedVersion_Issue is Maybe ObjRef type.

P.S. Last week, I decided to create  almost same module as RedmineHs and code some, but I thought someone might have done same thing and googled, thenI found your module. 
It's nice and thanks!

**Comment by lookunder** [comment]
Hi Yawata,

I added the Maybe and updated the code on github and the package on hackage.

Charles
