### ISSUE TITLE
Issue Custom field parse failure

### ISSUE THREAD

**Issue by averagehat** [lookunder/RedmineHs#5]
``` haskell
mng = RedmineMng "mysite"
issue' = getIssue mng 11730 $ fromList [("key", apikey)]

main = do
  x <- runMaybeT issue'
```

Gives error:

```
Error in $.issue['custom_fields'][0]: failed to parse field issue: failed to parse field custom_fields: key "value" not present
```

Site info:

```

Environment:
  Redmine version                2.6.1.stable
. . . . 
Redmine plugins:
  redmine_change_issue_author    0.0.1
  redmine_dmsf                   1.4.8 stable
  redmine_mail_reminder          2.6.5.0001
```

**Comment by lookunder** [comment]
Could you provide the custom_fields portion of the json when you run it in the browser. I would like to see in which case the value fails to parse.

**Comment by averagehat** [comment]
what would be the command as a url?

**Comment by lookunder** [comment]
For issue 22850 on the Redmine project site it is:
http://www.redmine.org/issues/22850.json.
You might have to add the key after with $key=yourkey.

You can find more info here:
http://www.redmine.org/projects/redmine/wiki/Rest_api.

On 5/20/2016 at 8:12 AM, "Mike Panciera"  wrote:what would be the
command as a url?

**Comment by averagehat** [comment]
11730.json

``` javascript
{"issue":{"id":11730,"project":{"id":18,"name":"Samples"},"tracker":{"id":6,"name":"Sample"},"status":{"id":1,"name":"New"},"priority":{"id":2,"name":"Normal"},"author":{"id":82,"name":"NGS Sync"},"subject":"CHIKVxOP6xVERO","start_date":"2016-05-10","done_ratio":0,"custom_fields":[{"id":29,"name":"AH3 Ct"},{"id":16,"name":"Accession","value":""},{"id":22,"name":"Date Received","value":""},{"id":11,"name":"Collaborator","value":""},{"id":12,"name":"Collection Date","value":""},{"id":10,"name":"CollectionLocation","value":""},{"id":17,"name":"Genbank Ready","value":"0"},{"id":19,"name":"PR Name"},{"id":21,"name":"Media","value":""},{"id":24,"name":"InfA Ct","value":""},{"id":25,"name":"InfB Ct"},{"id":26,"name":"RNaseP Ct"},{"id":27,"name":"swInfA Ct","value":""},{"id":28,"name":"swH1 Ct"},{"id":54,"name":"Tags","value":""},{"id":23,"name":"Study","value":""},{"id":9,"name":"SRNum","value":""},{"id":14,"name":"Sample Type","value":""},{"id":20,"name":"Synced Date","value":""},{"id":2,"name":"Needs Review","value":"0"},{"id":3,"name":"Pathogen","value":""}],"created_on":"2016-05-10T14:23:28Z","updated_on":"2016-05-10T14:23:28Z"}}
```

in a rush apologize for the formatting

**Comment by lookunder** [comment]
Some fields don't have a value like in 29 versus 16:
{
            "id": 29,
            "name": "AH3 Ct"
        },
        {
            "id": 16,
            "name": "Accession",
            "value": ""
        },

Do you know what kind of field it is? Changing it in the configuration
could fix it.
Else I could update the code to have an empty string value if none is
found.

On 5/20/2016 at 9:24 AM, "Mike Panciera"  wrote:

```
11730.json 

{"issue":{"id":11730,"project":{"id":18,"name":"Samples"},"tracker":{"id":6,"name":"Sample"},"status":{"id":1,"name":"New"},"priority":{"id":2,"name":"Normal"},"author":{"id":82,"name":"NGS
```

Sync"},"subject":"CHIKVxOP6xVERO","start_date":"2016-05-10","done_ratio":0,"custom_fields":[{"id":29,"name":"AH3
Ct"},{"id":16,"name":"Accession","value":""},{"id":22,"name":"Date
Received","value":""},{"id":11,"name":"Collaborator","value":""},{"id":12,"name":"Collection
Date","value":""},{"id":10,"name":"CollectionLocation","value":""},{"id":17,"name":"Genbank
Ready","value":"0"},{"id":19,"name":"PR
Name"},{"id":21,"name":"Media","value":""},{"id":24,"name":"InfA
Ct","value":""},{"id":25,"name":"InfB Ct"},{"id":26,"name":"RNaseP
Ct"},{"id":27,"name":"swInfA Ct","value":""},{"id":28,"name":"swH1
Ct"},{"id":54,"name":"Tags","value":""},{"id":23,"name":"Study","value":""},{"id":9,"name":"SRNum","value":""},{"id":14,"name":"Sample
Type","value"  :""},{"i  d":20,"name":"Synced
Date","value":""},{"id":2,"name":"Needs
Review","value":"0"},{"id":3,"name":"Pathogen","value":""}],"created_on":"2016-05-10T14:23:28Z","updated_on":"2016-05-10T14:23:28Z"}}

```
in a rush apologize for the formatting 

—
```

**Comment by averagehat** [comment]
I inherited this website configuration. I believe fields that have no value may be deprecated fields. I don't want to change the configuration because I may break one of our other scripts. Because it's a valid configuration, it should probably be valid in the haskell API too, even if it doesn't make much sense.

**Comment by lookunder** [comment]
I will update the code to process missing values as empty strings.

On ‎5‎/‎26‎/‎2016 at 8:32 AM, "Mike Panciera"  wrote:

```
I inherited this website configuration. I believe fields that have no
```

value may be deprecated fields. I don't want to change the
configuration because I may break one of our other scripts. Because
it's a valid configuration, it should probably be valid in the haskell
API too, even if it doesn't make much sense. 

```
—
```

**Comment by lookunder** [comment]
I have updated the code and uploaded a new version on Hackage. Can you give it a try?

**Comment by averagehat** [comment]
Yes, that fixed it, thanks.
